/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import VO.GerenteVO;
import VO.MedicamentosVO;
import controlador.MedicamentosControlador;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import modelo.medicamentosModel;


/**
 *
 * @author developer3
 */
public class Medicamentos extends javax.swing.JFrame {
private MedicamentosVO medicamentosVO;
    private MedicamentosControlador medicamentosContolador ;
   private medicamentosModel medicamentos;
    /**
     * Creates new form Medicamentos
     */
    public Medicamentos() {
        initComponents();
        medicamentosVO = new MedicamentosVO();
        medicamentosContolador = new MedicamentosControlador((medicamentosVO), this);
        medicamentos = new medicamentosModel(medicamentosVO);
                 
        
        jtable.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent Mouse_evt) {
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
                int row = table.rowAtPoint(point);
                if (Mouse_evt.getClickCount() == 1) {
                    Txtcodigo.setText(jtable.getValueAt(jtable.getSelectedRow(), 0).toString());
                    TxtNombre.setText(jtable.getValueAt(jtable.getSelectedRow(), 1).toString());
                    TxtCantidad.setText(jtable.getValueAt(jtable.getSelectedRow(), 2).toString());
                    TxtCura.setText(jtable.getValueAt(jtable.getSelectedRow(), 3).toString());
                    TxtPrecio.setText(jtable.getValueAt(jtable.getSelectedRow(), 4).toString());
                    CBTipo.setSelectedItem(jtable.getValueAt(jtable.getSelectedRow(), 5).toString());
                    CBPresentacion.setSelectedItem(jtable.getValueAt(jtable.getSelectedRow(), 6).toString());
                }

            }
        }
        
     );
        DefaultTableModel model = (DefaultTableModel) jtable.getModel();
        for (MedicamentosVO u : medicamentosContolador.listarMedicamento()) {
            String[] fila = {
                String.valueOf(u.getCodigo()),
                u.getNombre(),
                String.valueOf(u.getCantidad()),
                u.getCura(),
                String.valueOf(u.getPrecio()),
                u.getTipo(),
                u.getPresentacion()};
                model.addRow(fila);
        }
        ListSelectionModel listusuario;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnRegistrar = new javax.swing.JButton();
        TxtCura = new javax.swing.JTextField();
        BtnLimpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        TxtPrecio = new javax.swing.JTextField();
        BtnActualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        BtnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        txtFiltro = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        CBTipo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtCantidad = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        CBFiltro = new javax.swing.JComboBox<>();
        CBPresentacion = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        Txtcodigo = new javax.swing.JTextField();
        txtMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Tipo:");

        jLabel3.setText("Cura:");

        BtnRegistrar.setBackground(new java.awt.Color(204, 255, 204));
        BtnRegistrar.setText("Registrar");
        BtnRegistrar.setName("BtnRegistrar"); // NOI18N
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });

        TxtCura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCuraActionPerformed(evt);
            }
        });

        BtnLimpiar.setBackground(new java.awt.Color(204, 255, 255));
        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio:");

        TxtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrecioActionPerformed(evt);
            }
        });

        BtnActualizar.setBackground(new java.awt.Color(255, 255, 204));
        BtnActualizar.setText("Actualizar");
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });

        jLabel7.setText("Ingrese un dato para consultar:");

        BtnBuscar.setBackground(new java.awt.Color(204, 255, 255));
        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Cantidad", "Cura", "Precio", "Tipo", "Presentación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtable.setName(""); // NOI18N
        jScrollPane1.setViewportView(jtable);

        txtFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroActionPerformed(evt);
            }
        });

        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });

        CBTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Analgésicos", "Antiácidos", "Antialérgicos", "Laxantes", "Antiinfecciosos", "Antiinflamatorios", "Antipiréticos", "Antitusivos" }));

        jLabel8.setText("Nombre:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Medicamentos");

        TxtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCantidadActionPerformed(evt);
            }
        });

        jLabel9.setText("Cantidad:");

        CBFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Nombre", "Tipo", "Presentación" }));

        CBPresentacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Ampolletas", "Pastas", "Jarabe" }));

        jLabel10.setText("Presentación:");

        codigo.setBorder(null);
        codigo.setMaximumSize(new java.awt.Dimension(0, 0));
        codigo.setMinimumSize(new java.awt.Dimension(0, 0));
        codigo.setName(""); // NOI18N
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });

        Txtcodigo.setBorder(null);
        Txtcodigo.setMaximumSize(new java.awt.Dimension(0, 0));
        Txtcodigo.setMinimumSize(new java.awt.Dimension(0, 0));
        Txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtcodigoActionPerformed(evt);
            }
        });

        txtMenu.setText("MENU");
        txtMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtCura, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(BtnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CBPresentacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(Txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(291, 291, 291)
                                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMenu)
                                .addGap(8, 8, 8)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 42, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(CBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(CBPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxtCura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnLimpiar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnActualizar)
                    .addComponent(BtnRegistrar)
                    .addComponent(jLabel4)
                    .addComponent(TxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscar)
                    .addComponent(CBFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
 if ((TxtNombre.getText().equals("")) || (TxtCantidad.getText().equals("")) || (TxtCura.getText().equals("")) || (TxtPrecio.getText().equals("")) || (CBTipo.getSelectedItem().equals("Seleccione...")) || (CBPresentacion.getSelectedItem().equals("Seleccione..."))) {
            JOptionPane.showMessageDialog(this, "No puedes dejar campos Vacios");
        } else {
            medicamentosVO.setNombre(TxtNombre.getText());
            medicamentosVO.setCantidad(Integer.parseInt(TxtCantidad.getText()));
            medicamentosVO.setCura(TxtCura.getText());
            medicamentosVO.setPrecio(Integer.parseInt(TxtPrecio.getText()));
            medicamentosVO.setPresentacion((String)CBPresentacion.getSelectedItem());
            medicamentosVO.setTipo((String)CBTipo.getSelectedItem());
            medicamentosContolador.InMedicamento();
               

                DefaultTableModel tb = (DefaultTableModel) jtable.getModel();
                int a = jtable.getRowCount() - 1;
                for (int i = a; i >= 0; i--) {
                    tb.removeRow(tb.getRowCount() - 1);
                }

                DefaultTableModel model = (DefaultTableModel) jtable.getModel();
        for (MedicamentosVO u : medicamentosContolador.listarMedicamento()) {
            String[] fila = {
                String.valueOf(u.getCodigo()),
                u.getNombre(),
                String.valueOf(u.getCantidad()),
                u.getCura(),
                String.valueOf(u.getPrecio()),
                u.getTipo(),
                u.getPresentacion()};
                model.addRow(fila);
        }
    
      TxtNombre.setText("");
      TxtCantidad.setText("");
      TxtCura.setText("");
      TxtPrecio.setText("");
      CBTipo.setSelectedIndex(0);
      CBPresentacion.setSelectedIndex(0);
      
      }
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void TxtCuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCuraActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        // TODO add your handling code here:
       
        TxtNombre.setText("");
      TxtCantidad.setText("");
      TxtCura.setText("");
      TxtPrecio.setText("");
      CBTipo.setSelectedIndex(0);
      CBPresentacion.setSelectedIndex(0);
      txtFiltro.setText("");
       CBFiltro.setSelectedIndex(0);
      
       DefaultTableModel tb = (DefaultTableModel) jtable.getModel();
                int a = jtable.getRowCount() - 1;
                for (int i = a; i >= 0; i--) {
                    tb.removeRow(tb.getRowCount() - 1);
                }

                DefaultTableModel model = (DefaultTableModel) jtable.getModel();
        for (MedicamentosVO u : medicamentosContolador.listarMedicamento()) {
            String[] fila = {
                String.valueOf(u.getCodigo()),
                u.getNombre(),
                String.valueOf(u.getCantidad()),
                u.getCura(),
                String.valueOf(u.getPrecio()),
                u.getTipo(),
                u.getPresentacion()};
                model.addRow(fila);
        }
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void TxtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrecioActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
if ((txtFiltro.getText().equals("")) || (CBFiltro.getSelectedItem().equals("seleccione..."))){
            JOptionPane.showMessageDialog(this, "No puedes dejar campos Vacios en el filtro");
        } else {
    
            String Consulta = txtFiltro.getText();
            String filtro = ((String)CBFiltro.getSelectedItem());
            
                DefaultTableModel tb = (DefaultTableModel) jtable.getModel();
                int a = jtable.getRowCount() - 1;
                for (int i = a; i >= 0; i--) {
                    tb.removeRow(tb.getRowCount() - 1);
                }

                DefaultTableModel model = (DefaultTableModel) jtable.getModel();
                for (MedicamentosVO u : medicamentosContolador.ConFiltro(filtro, Consulta)){
                     String[] fila = {
                String.valueOf(u.getCodigo()),
                u.getNombre(),
                String.valueOf(u.getCantidad()),
                u.getCura(),
                String.valueOf(u.getPrecio()),
                u.getTipo(),
                u.getPresentacion()};
                model.addRow(fila);
                }
                }
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void txtFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroActionPerformed

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    private void TxtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCantidadActionPerformed

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed

    private void TxtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtcodigoActionPerformed

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        // TODO add your handling code here:
        if ((TxtNombre.getText().equals("")) || (TxtCantidad.getText().equals("")) || (TxtCura.getText().equals("")) || (TxtPrecio.getText().equals("")) || (CBTipo.getSelectedItem().equals("Seleccione...")) || (CBPresentacion.getSelectedItem().equals("Seleccione..."))) {
            JOptionPane.showMessageDialog(this, "No puedes dejar campos Vacios");
        } else {
            medicamentosVO.setCodigo(Integer.parseInt(Txtcodigo.getText()));
            medicamentosVO.setNombre(TxtNombre.getText());
            medicamentosVO.setCantidad(Integer.parseInt(TxtCantidad.getText()));
            medicamentosVO.setCura(TxtCura.getText());
            medicamentosVO.setPrecio(Integer.parseInt(TxtPrecio.getText()));
            medicamentosVO.setPresentacion((String)CBPresentacion.getSelectedItem());
            medicamentosVO.setTipo((String)CBTipo.getSelectedItem());
            medicamentosContolador.UpdateMedicamento();
               

                DefaultTableModel tb = (DefaultTableModel) jtable.getModel();
                int a = jtable.getRowCount() - 1;
                for (int i = a; i >= 0; i--) {
                    tb.removeRow(tb.getRowCount() - 1);
                }

                DefaultTableModel model = (DefaultTableModel) jtable.getModel();
        for (MedicamentosVO u : medicamentosContolador.listarMedicamento()) {
            String[] fila = {
                String.valueOf(u.getCodigo()),
                u.getNombre(),
                String.valueOf(u.getCantidad()),
                u.getCura(),
                String.valueOf(u.getPrecio()),
                u.getTipo(),
                u.getPresentacion()};
                model.addRow(fila);
        }
    
      TxtNombre.setText("");
      TxtCantidad.setText("");
      TxtCura.setText("");
      TxtPrecio.setText("");
      CBTipo.setSelectedIndex(0);
      CBPresentacion.setSelectedIndex(0);
      
      }
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void txtMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMenuActionPerformed
        // TODO add your handling code here:
                        Menu_Administrador menu = new Menu_Administrador();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_txtMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medicamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JComboBox<String> CBFiltro;
    private javax.swing.JComboBox<String> CBPresentacion;
    private javax.swing.JComboBox<String> CBTipo;
    private javax.swing.JTextField TxtCantidad;
    private javax.swing.JTextField TxtCura;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtPrecio;
    private javax.swing.JTextField Txtcodigo;
    private javax.swing.JTextField codigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jtable;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JButton txtMenu;
    // End of variables declaration//GEN-END:variables
}
